### ISSUE TITLE
Faibiodefilippo/linuxallremote


### ISSUE THREAD

**Issue by anony102197** [FabioDefilippo/linuxallremote#1]

**Comment by FabioDefilippo** [comment]
please, could you write or explain the issue you experienced?

**Comment by anony102197** [comment]
> please, could you write or explain the issue you experienced?

Fra ma puoi parlare anche in italiano eh. Cmq so come finziala l'app di github! Ho sempre scaricato i tool dal sito lol.

**Comment by FabioDefilippo** [comment]
ok, ti ringrazio, ma non posso sapere che tu sia italiano.
